### ISSUE TITLE
Problem with the last journey pattern

### ISSUE THREAD

**Issue by skinkie** [firstflamingo/TimetableBrowser#5]
After browsing to the last operator in the file. Going for the last JourneyPattern in the file. The application shows the rotating rainbow. Probably something is wrong with a comparison. I am eager to know in which part of the code that is.

I have breaked the code at:
https://github.com/firstflamingo/rrrr_cocoa_wrapper/blob/master/OVJourneyPattern.m#L108

**Comment by skinkie** [comment]
p self.nrOfVehicleJourneys
(NSUInteger) $2 = 4294651513

That is a good clue something is wrong.

**Comment by skinkie** [comment]
I wouldn't be suprised if:

``` ObjC
- (NSUInteger)nrOfVehicleJourneys
{
    return self.nextPattern.vj_ids_offset - self.pattern.vj_ids_offset;
}

- (journey_pattern_t)nextPattern
{
    return self.ctx->journey_patterns[self.index + 1];
}
```

Would cause the problems.

**Comment by bschotanus** [comment]
Great debugging ;-)
There must be a better way to deduce nrOfVehicleJourneys from tdata...

**Comment by skinkie** [comment]
Already commited ;)

**Comment by bschotanus** [comment]
Well done!
